name: Hadolint                                                            # Define the name of the workflow

on: [push, pull_request]                                                  # Trigger the workflow on push and pull request events

jobs:                                                                     # Initialise job
  lint:                                                                   # Define a job named 'lint'
    runs-on: ubuntu-latest                                                # Specify the type of virtual machine to use (Ubuntu latest version)

    container:                                                            # Set container image
      image: monkeyknuckles/hadolint                                      # Points to Hadolint container

    steps:                                                                # List of steps to execute
      - name: Checkout code                                               # Checkout code label text
        uses: actions/checkout@v3                                         # Use the checkout action to clone the repository

      - name: Copy Hadolint config                                        # Copy Hadolint configuration file label text
        run: cp /app/.hadolint.yaml $GITHUB_WORKSPACE                     # Copy the .hadolint.yaml file from the container to the workspace

      - name: Run Lint Hadolint                                           # Set lint Hadolint label text
        run: >                                                            # Lint all dockerfiles
             find . \( -iname "dockerfile"                                 
             -or -name "*.dockerfile" \)
             -exec hadolint {} +  
  
      